version: '3.4'
services:
  client-app:
    image: client
    ports:
      - '3000:3000'
    expose:
      - '3000'
  server:
    image: server
    ports:
      - '5000:5000'
    expose:
      - '5000'      